name: "Zephyr Z_Motion CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  board:
    uses: catie-aq/zephyr_workflows/.github/workflows/board.yml@main
    with:
      board: "z_motion"

    secrets:
      personal_access_token: ${{ secrets.CI_6TRON_ZEPHYR_RO }}
